### PR TITLE
Updates of some stuffs.

### PR DESCRIPTION
**Pull request by qogusdn1017**
---

Decorated Readme.md because it's too blank. Added information about depend and some kind of stuffs.

Also edited gradle.properties and plugin.yml.

If it has any problem or error, contact me with Discord.

END OF THIS PULL REQUEST DESCRIPTION.

---

### CODE REVIEW

**Comment by qogusdn1017** [comment]
Think you're not accepting my pull request. So I'll close this.

**Comment by B1ackAnge1** [comment]
감사합니다. 다음 수정에 반양할테니 Open으로 수정해주세요.

**Comment by qogusdn1017** [comment]
ㅇ 근데 제 플긴으로 하니 오류뜨네요 알아서 수정하시길..
+ 안받는거 같아서 레포 지워가지고 안됨

**Comment by qogusdn1017** [comment]
# Basic-Tools 
--- 
**[B1ackAnge1](https://github.com/B1ackAnge1)**'s First Minecraft Plugin for **[Paper](https://papermc.io).** 

Written in **[Kotlin](https://kotlinlang.org)**, depend on **[Tap](https://github.com/noonmaru/Tap)** & **[Kotlin](https://github.com/noonmaru/kotlin-plugin)** 

API Version as Paper 1.13.2. 
---

**Comment by qogusdn1017** [comment]
리드미 Raw는 있어서 드림. 나머지파일은 제가 실수해서 오류날수도 있으니 확인하고 복붙하셔용

**Pull request closed without merging**
